"""empty message

Revision ID: 3362e3dc0a95
Revises: 5d8716a728f4
Create Date: 2021-05-15 21:11:40.109539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3362e3dc0a95'
down_revision = '5d8716a728f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=7), nullable=False),
    sa.Column('subject_teacher', sa.String(length=7), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subject_teacher'], ['user.user_id'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('subject')
    # ### end Alembic commands ###
