"""empty message

Revision ID: 5d8716a728f4
Revises: 
Create Date: 2021-05-14 20:55:29.385326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8716a728f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=255), nullable=False),
    sa.Column('news_message', sa.String(length=255), nullable=False),
    sa.Column('news_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.String(length=7), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=7), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=7), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_role'], ['role.role_id'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('news')
    # ### end Alembic commands ###
