"""empty message

Revision ID: a5652e342f87
Revises: 14c909d4c30f
Create Date: 2021-05-16 18:30:18.935723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5652e342f87'
down_revision = '14c909d4c30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile__employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telp', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telp'),
    sa.UniqueConstraint('telp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile__employee')
    # ### end Alembic commands ###
