"""empty message

Revision ID: f176d20943ad
Revises: 
Create Date: 2021-05-17 21:16:00.836509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f176d20943ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=7), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id'),
    sa.UniqueConstraint('class_id'),
    sa.UniqueConstraint('class_name'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=255), nullable=False),
    sa.Column('news_message', sa.String(length=255), nullable=False),
    sa.Column('news_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.String(length=7), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=7), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=7), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_role'], ['role.role_id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile__employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=7), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telp', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['user.user_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telp'),
    sa.UniqueConstraint('telp')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=7), nullable=False),
    sa.Column('subject_teacher', sa.String(length=7), nullable=True),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subject_teacher'], ['user.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id'),
    sa.UniqueConstraint('subject_id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.String(length=7), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('about_topic', sa.String(length=255), nullable=True),
    sa.Column('assignment', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_class', sa.String(length=7), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['schedule_class'], ['class.class_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject'], ['subject.subject_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('module')
    op.drop_table('subject')
    op.drop_table('profile__employee')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('news')
    op.drop_table('class')
    # ### end Alembic commands ###
