"""empty message

Revision ID: f64a503b1fe2
Revises: 
Create Date: 2021-05-14 13:30:03.384805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64a503b1fe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.String(length=7), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=7), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=7), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_role'], ['role.role_id'], onupdate='CASCADE', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
